app:
  name: test_app
  mode: dev
  data_center_id: 1
  machine_id: 1
  debug: true

server:
  port: 8080
  prefix: /api
  cores:
    enabled: true
    allow_origins: ["*"]
    allow_methods: ["GET", "POST", "PUT", "DELETE"]
    allow_headers: ["*"]
    expose_headers: ["*"]

log:
  level: debug
  path: /web_app/logs
  filename: web_app.log
  max_size: 20
  max_age: 30
  max_backups: 5

database:
  type: mysql
  host: localhost
  port: 3306
  name: bluebell
  user: root
  password: 123456

#redis:
#  host: localhost
#  port: 6379

email:
  name: test
  user: 1840586637@qq.com
  password: 123456
  host: smtp.qq.com
  port: 465